name: CI/CD Pipeline

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-and-test:
    name: Check Code Style & Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: List files in current directory before checkout
        run: |
          ls -al

      - name: Check out repository
        uses: actions/checkout@v2

      - name: List files in current directory after checkout
        run: |
          ls -al

      - name: Install dependencies
        run: |
          # Example for Python
          echo "Installing dependencies..."

      - name: List files in current directory after installing dependencies
        run: |
          ls -al

      - name: Check style
        run: |
          # Check coding style
          echo "Checking coding style..."

      - name: Analyse the code
        run: |
          # Analyse the code
          echo "Analysing the code..."

      - name: Run tests
        run: |
          # Run unit tests
          echo "Running unit tests..."

  build-docker-image:
    name: Build & Push Docker Image
    needs: [check-and-test]  # depends on coding style and tests passing
    runs-on: ubuntu-latest
    steps:
      - name: List files in current directory before checkout
        run: |
          ls -al

      - name: Check out repository
        uses: actions/checkout@v2

      - name: List files in current directory after checkout
        run: |
          ls -al

      - name: Log into Docker registry
        run: |
          echo "Logging in into Docker registry..."

      - name: Build Docker image
        run: |
          echo "Building Docker image..."

      - name: Tag & push Docker image
        run: |
          echo "Tagging and pushing Docker image..."
          echo "Pushing Docker image..."

  deploy-migration:
    name: Run Migration
    needs: [build-docker-image]  # must happen after the image is built
    environment: production  # "production" environment with required approval
    runs-on: ubuntu-latest
    steps:
      - name: List files in current directory before running migration
        run: |
          ls -al

      - name: Run migration
        run: |
          # Example command to run migration in a container
          echo "Running migration..."

  deploy-docker-swarm:
    name: Deploy to Docker Swarm
    needs: [deploy-migration]  # only run if migration succeeds
    environment: production  # "production" environment with required approval
    runs-on: ubuntu-latest
    steps:
      - name: List files in current directory before deploying to Docker Swarm
        run: |
          ls -al

      - name: Deploy service to Docker Swarm
        run: |
          # Example of a Docker Swarm update
          echo "Deploying images to Docker Swarm..."
